# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 01:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('lastAmount', models.IntegerField(default=0)),
                ('changeAmount', models.IntegerField(default=0)),
                ('remainAmount', models.IntegerField(default=0)),
                ('operator', models.CharField(max_length=20, null=True)),
                ('change_reason', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'conin_change_log',
            },
        ),
        migrations.CreateModel(
            name='MoneyChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('lastAmount', models.IntegerField(default=0)),
                ('ChangeAmount', models.IntegerField(default=0)),
                ('remainAmount', models.IntegerField(default=0)),
                ('operator', models.CharField(max_length=20, null=True)),
                ('change_reason', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'money_change_log',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='moneychangelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='money_change_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coinchangelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coin_change_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
