# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0002_auto_20180422_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneychangelog',
            old_name='ChangeAmount',
            new_name='changeAmount',
        ),
    ]
