# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxerIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('real_name', models.CharField(max_length=10)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('birthday', models.DateTimeField()),
                ('identity_number', models.CharField(max_length=18)),
                ('mobile', models.CharField(max_length=11)),
                ('is_professional_boxer', models.BooleanField(default=False)),
                ('club', models.CharField(max_length=128)),
                ('introduction', models.TextField()),
                ('experience', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boxer_identification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bxer_identification',
            },
        ),
        migrations.CreateModel(
            name='BoxerMediaAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('media_url', models.URLField()),
                ('media_type', models.CharField(choices=[(b'CERTIFICATE_OF_HONOR', '\u8363\u8a89\u8bc1\u4e66'), (b'CONTENSTANT_VIDEO', '\u53c2\u8d5b\u89c6\u9891')], max_length=30)),
                ('boxer_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxer_identification_additional', to='biz.BoxerIdentification')),
            ],
            options={
                'db_table': 'boxer_identification_additional',
            },
        ),
    ]
