# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0002_message'),
        ('biz', '0002_auto_20180424_2138'),
    ]

    operations = [
    ]
