# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 04:12
from __future__ import unicode_literals

import biz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0002_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=140)),
                ('images', biz.models.StringListField()),
                ('video', models.URLField()),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'discover_message',
            },
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
