# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0003_auto_20180425_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_time',)},
        ),
    ]
