# Generated by Django 2.0.4 on 2018-04-27 10:00

import biz.validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0003_auto_20180425_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140)),
                ('ancestor_id', models.IntegerField(db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'discover_comment',
                'ordering': ('-created_time',),
            },
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_time',)},
        ),
        migrations.AlterField(
            model_name='coinchangelog',
            name='change_type',
            field=models.CharField(choices=[('INCREASE_COIN_RECHARGE', '收入-充值'), ('INCREASE_COIN_OFFICIAL_RECHARGE', '官方充值'), ('INCREASE_GUESSING_AWARD', '竞猜奖励'), ('INCREASE_USER_DONATE', '收入-用户打赏'), ('INCREASE_USER_VIDEO_DONATE', '收入-用户视频打赏'), ('INCREASE_COIN_REJECT_WITHDRAW_REBACK', '提现被拒绝-退回款项'), ('INCREASE_WITHDRAW_FAILED_REBACK', '提现失败-退回款项'), ('REDUCE_USER_DONATE', '支出-用户打赏'), ('REDUCE_USER_VIDEO_DONATE', '支出-用户视频打赏'), ('REDUCE_SHOPPING_EXCHANGE', '商城兑换'), ('REDUCE_GUESSING_BET', '竞猜下注'), ('REDUCE_START_VOTE', '支出明星投票'), ('REDUCE_WITHDRAW_APPLY', '提现申请提现')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='moneychangelog',
            name='change_type',
            field=models.CharField(choices=[('INCREASE_MONEY_RECHARGE', '充值'), ('INCREASE_MONEY_OFFICIAL_RECHARGE', '官方充值'), ('INCREASE_ORDER', '约单(收入)'), ('INCREASE_MONEY_REJECT_WITHDRAW_REBACK', '提现(审核未通过)'), ('REDUCE_WITHDRAW', '提现'), ('REDUCE_ORDER', '约单(支出)'), ('REDUCE_PAY_FOR_VIDEO', '付费视频'), ('REDUCE_SIGN_UP', '报名')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(db_index=True, error_messages={'unique': '手机号已存在。'}, max_length=11, unique=True, validators=[biz.validator.validate_mobile]),
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='biz.Message'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biz.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
