# Generated by Django 2.0.4 on 2018-04-29 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0004_auto_20180427_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='biz.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discover_like',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.SmallIntegerField(choices=[(1, '淫秽色情'), (2, '赌博诈骗'), (3, '恐怖暴力'), (4, '违法信息'), (5, '诽谤辱骂'), (6, '垃圾广告'), (7, '其他')])),
                ('remark', models.CharField(max_length=20, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='biz.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discover_report',
                'ordering': ('-created_time',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'message')},
        ),
    ]
