# Generated by Django 2.0.4 on 2018-04-28 13:58

import biz.validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0004_auto_20180426_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxerIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('real_name', models.CharField(max_length=10)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('birthday', models.DateTimeField()),
                ('identity_number', models.CharField(max_length=18)),
                ('mobile', models.CharField(max_length=11)),
                ('is_professional_boxer', models.BooleanField(default=False)),
                ('club', models.CharField(blank=True, max_length=50, null=True)),
                ('job', models.CharField(max_length=10)),
                ('introduction', models.TextField(max_length=300)),
                ('experience', models.TextField(blank=True, max_length=500, null=True)),
                ('authentication_state', models.CharField(choices=[('WAITING', '待审核'), ('REFUSE', '已驳回'), ('APPROVED', '已通过')], default='WAITING', max_length=10)),
                ('lock_state', models.CharField(choices=[('LOCKED', '已锁定'), ('UNLOCKED', '已解锁')], default='LOCKED', max_length=10)),
            ],
            options={
                'db_table': 'boxer_identification',
            },
        ),
        migrations.CreateModel(
            name='BoxerMediaAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('media_url', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('CERTIFICACONTESTANTTE_OF_HONOR', '荣誉证书'), ('CONTESTANT_VIDEO', '参赛视频')], max_length=30)),
                ('boxer_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxer_identification_additional', to='biz.BoxerIdentification')),
            ],
            options={
                'db_table': 'boxer_identification_additional',
            },
        ),
        migrations.AlterField(
            model_name='coinchangelog',
            name='change_type',
            field=models.CharField(choices=[('INCREASE_COIN_RECHARGE', '收入-充值'), ('INCREASE_COIN_OFFICIAL_RECHARGE', '官方充值'), ('INCREASE_GUESSING_AWARD', '竞猜奖励'), ('INCREASE_USER_DONATE', '收入-用户打赏'), ('INCREASE_USER_VIDEO_DONATE', '收入-用户视频打赏'), ('INCREASE_COIN_REJECT_WITHDRAW_REBACK', '提现被拒绝-退回款项'), ('INCREASE_WITHDRAW_FAILED_REBACK', '提现失败-退回款项'), ('REDUCE_USER_DONATE', '支出-用户打赏'), ('REDUCE_USER_VIDEO_DONATE', '支出-用户视频打赏'), ('REDUCE_SHOPPING_EXCHANGE', '商城兑换'), ('REDUCE_GUESSING_BET', '竞猜下注'), ('REDUCE_START_VOTE', '支出明星投票'), ('REDUCE_WITHDRAW_APPLY', '提现申请提现')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='moneychangelog',
            name='change_type',
            field=models.CharField(choices=[('INCREASE_MONEY_RECHARGE', '充值'), ('INCREASE_MONEY_OFFICIAL_RECHARGE', '官方充值'), ('INCREASE_ORDER', '约单(收入)'), ('INCREASE_MONEY_REJECT_WITHDRAW_REBACK', '提现(审核未通过)'), ('REDUCE_WITHDRAW', '提现'), ('REDUCE_ORDER', '约单(支出)'), ('REDUCE_PAY_FOR_VIDEO', '付费视频'), ('REDUCE_SIGN_UP', '报名')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(db_index=True, error_messages={'unique': '手机号已存在。'}, max_length=11, unique=True, validators=[biz.validator.validate_mobile]),
        ),
        migrations.AddField(
            model_name='boxeridentification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boxer_identification', to=settings.AUTH_USER_MODEL),
        ),
    ]
