# Generated by Django 2.0.4 on 2018-04-28 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0004_auto_20180427_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxerIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('real_name', models.CharField(max_length=10)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('birthday', models.DateTimeField()),
                ('identity_number', models.CharField(max_length=18)),
                ('mobile', models.CharField(max_length=11)),
                ('is_professional_boxer', models.BooleanField(default=False)),
                ('club', models.CharField(blank=True, max_length=50, null=True)),
                ('job', models.CharField(max_length=10)),
                ('introduction', models.TextField(max_length=300)),
                ('experience', models.TextField(blank=True, max_length=500, null=True)),
                ('authentication_state', models.CharField(choices=[('WAITING', '待审核'), ('REFUSE', '已驳回'), ('APPROVED', '已通过')], default='WAITING', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boxer_identification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'boxer_identification',
            },
        ),
        migrations.CreateModel(
            name='BoxerMediaAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('media_url', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('CERTIFICATE_OF_HONOR', '荣誉证书'), ('CONTESTANT_VIDEO', '参赛视频')], max_length=30)),
                ('boxer_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxer_identification_additional', to='biz.BoxerIdentification')),
            ],
            options={
                'db_table': 'boxer_identification_additional',
            },
        ),
    ]
