# Generated by Django 2.0.4 on 2018-05-04 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0005_auto_20180504_1036'),
        ('biz', '0005_auto_20180429_1017'),
    ]

    operations = [
    ]
