# Generated by Django 2.0.4 on 2018-05-04 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0005_auto_20180429_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('object_type', models.SmallIntegerField(db_index=True)),
                ('reason', models.SmallIntegerField(choices=[(1, '淫秽色情'), (2, '赌博诈骗'), (3, '恐怖暴力'), (4, '违法信息'), (5, '诽谤辱骂'), (6, '垃圾广告'), (7, '其他')])),
                ('remark', models.CharField(max_length=20, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discover_report',
                'ordering': ('-created_time',),
            },
        ),
    ]
