# Generated by Django 2.0.4 on 2018-05-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0005_auto_20180429_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11)),
                ('template_code', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=512)),
                ('business_id', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'sms_log',
                'ordering': ('-created_time',),
            },
        ),
    ]
