# Generated by Django 2.0.4 on 2018-05-01 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0005_boxeridentification_boxermediaadditional'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationOperateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('approve_state', models.CharField(blank=True, choices=[('WAITING', '待审核'), ('REFUSE', '已驳回'), ('APPROVED', '已通过')], max_length=10, null=True)),
                ('lock_state', models.BooleanField(default=False)),
                ('operator_comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='boxeridentification',
            old_name='authentication_state',
            new_name='approve_state',
        ),
        migrations.AlterField(
            model_name='boxeridentification',
            name='lock_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identificationoperatelog',
            name='identification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operate_log', to='biz.BoxerIdentification'),
        ),
        migrations.AddField(
            model_name='identificationoperatelog',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='operate_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
