# Generated by Django 2.0.4 on 2018-05-07 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0006_merge_20180504_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('THAI_BOXING', '泰拳'), ('MMA', 'MMA'), ('BOXING', '拳击')], max_length=20)),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('validity', models.DateField()),
                ('boxer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='biz.BoxerIdentification')),
            ],
        ),
    ]
