# Generated by Django 2.0.4 on 2018-05-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0007_report'),
        ('biz', '0006_smslog'),
    ]

    operations = [
    ]
