# Generated by Django 2.0.4 on 2018-05-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0008_merge_20180507_1902'),
        ('biz', '0007_auto_20180507_1757'),
    ]

    operations = [
    ]
