# Generated by Django 2.0.4 on 2018-05-04 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0008_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('-created_time',)},
        ),
        migrations.AlterModelTable(
            name='follow',
            table='discover_follow',
        ),
    ]
