# Generated by Django 2.0.4 on 2018-05-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0009_merge_20180507_1919'),
        ('biz', '0009_merge_20180507_1928'),
    ]

    operations = [
    ]
