# Generated by Django 2.0.4 on 2018-05-10 04:31

import biz.models
import biz.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0011_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxingClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('club_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('phone', models.CharField(max_length=11, validators=[biz.validator.validate_mobile])),
                ('opening_hours', models.CharField(max_length=30)),
                ('images', biz.models.StringListField()),
                ('introduction', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'club',
            },
        ),
    ]
