# Generated by Django 2.0.4 on 2018-05-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0012_auto_20180509_1920'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
    ]
