# Generated by Django 2.0.4 on 2018-05-10 11:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0012_auto_20180509_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=140)),
                ('url', models.CharField(max_length=200)),
                ('try_url', models.CharField(max_length=200)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_show', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hot_video',
                'ordering': ('-created_time',),
            },
        ),
    ]
