# Generated by Django 2.0.4 on 2018-05-14 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0013_boxingclub'),
        ('biz', '0013_hotvideo_hotvideoorder'),
    ]

    operations = [
    ]
