# Generated by Django 2.0.4 on 2018-05-14 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0013_auto_20180510_1755'),
        ('biz', '0013_hotvideo_hotvideoorder'),
    ]

    operations = [
    ]
