# Generated by Django 2.0.5 on 2018-05-14 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0014_merge_20180514_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotvideo',
            name='is_show',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='hotvideo',
            name='operator',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
