# Generated by Django 2.0.4 on 2018-05-14 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0014_merge_20180514_1056'),
        ('biz', '0013_auto_20180510_1755'),
    ]

    operations = [
    ]
