# Generated by Django 2.0.4 on 2018-05-14 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0014_merge_20180514_1126'),
        ('biz', '0015_merge_20180514_1104'),
    ]

    operations = [
    ]
