# Generated by Django 2.0.4 on 2018-05-14 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0016_merge_20180514_1221'),
        ('biz', '0015_auto_20180514_1653'),
    ]

    operations = [
    ]
