# Generated by Django 2.0.5 on 2018-05-16 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('biz', '0017_merge_20180514_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.SmallIntegerField(choices=[(1, '未支付'), (2, '已支付')], db_index=True, default=1)),
                ('out_trade_no', models.BigIntegerField()),
                ('payment_type', models.SmallIntegerField(choices=[(1, '支付宝'), (2, '微信'), (3, '余额')])),
                ('amount', models.PositiveIntegerField()),
                ('device', models.SmallIntegerField(choices=[(1, 'iOS'), (2, 'Android')])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pay_order',
            },
        ),
    ]
