# Generated by Django 2.0.5 on 2018-05-17 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0018_payorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxingclub',
            old_name='club_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='payorder',
            old_name='created_time',
            new_name='order_time',
        ),
        migrations.RemoveField(
            model_name='payorder',
            name='update_time',
        ),
        migrations.AddField(
            model_name='course',
            name='club',
            field=models.ForeignKey(db_index=False, default=20, on_delete=django.db.models.deletion.PROTECT, to='biz.BoxingClub'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payorder',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='payorder',
            name='pay_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hotvideoorder',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未支付'), (2, '待使用'), (3, '待评论'), (4, '已完成'), (5, '已过期')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='payorder',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未支付'), (2, '待使用'), (3, '待评论'), (4, '已完成'), (5, '已过期')], db_index=True, default=1),
        ),
    ]
