# Generated by Django 2.0.5 on 2018-05-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0018_payorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payorder',
            options={'ordering': ('-created_time',)},
        ),
        migrations.AlterModelTable(
            name='payorder',
            table='pay_order',
        ),
    ]
