# Generated by Django 2.0.4 on 2018-05-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0018_payorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
