# Generated by Django 2.0.5 on 2018-05-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0018_auto_20180516_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorder',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未支付'), (2, '待使用'), (3, '待评论'), (4, '已完成'), (5, '已过期')], db_index=True, default=1),
        ),
    ]
