# Generated by Django 2.0.5 on 2018-05-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0018_payorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payorder',
            old_name='created_time',
            new_name='order_time',
        ),
        migrations.RemoveField(
            model_name='payorder',
            name='update_time',
        ),
        migrations.AddField(
            model_name='payorder',
            name='pay_time',
            field=models.DateTimeField(default='2018-05-08 06:13:51.046284'),
            preserve_default=False,
        ),
    ]
