# Generated by Django 2.0.4 on 2018-05-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0019_auto_20180518_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
