# Generated by Django 2.0.5 on 2018-05-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0019_auto_20180518_1520'),
        ('biz', '0019_auto_20180518_1439'),
    ]

    operations = [
    ]
