# Generated by Django 2.0.5 on 2018-05-18 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0020_merge_20180518_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=50)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('initial_views_count', models.PositiveIntegerField(default=0)),
                ('picture', models.CharField(max_length=200)),
                ('stay_top', models.BooleanField(default=False)),
                ('push_news', models.BooleanField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('app_content', models.TextField()),
                ('share_content', models.TextField(null=True)),
                ('operator', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_news',
                'ordering': ('-created_time',),
            },
        ),
        migrations.AddField(
            model_name='hotvideo',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hotvideo',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
