# Generated by Django 2.0.5 on 2018-05-18 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0020_merge_20180518_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxingclub',
            old_name='club_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='club',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='biz.BoxingClub'),
        ),
        migrations.AddField(
            model_name='payorder',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
    ]
