# Generated by Django 2.0.5 on 2018-05-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0021_auto_20180518_1657'),
        ('biz', '0021_auto_20180518_1640'),
    ]

    operations = [
    ]
