# Generated by Django 2.0.4 on 2018-05-21 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0021_auto_20180518_1657'),
        ('biz', '0021_auto_20180518_1640'),
    ]

    operations = [
    ]
