# Generated by Django 2.0.5 on 2018-05-21 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('biz', '0022_merge_20180521_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamenews',
            options={'ordering': ('-stay_top', '-created_time')},
        ),
        migrations.RemoveField(
            model_name='report',
            name='object_type',
        ),
        migrations.AddField(
            model_name='report',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='operator',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未处理'), (2, '核实为假'), (3, '已删除')], default=1),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='operator',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotvideo',
            name='operator',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='report',
            table='report',
        ),
    ]
