# Generated by Django 2.0.5 on 2018-05-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0022_merge_20180521_1204'),
        ('biz', '0022_merge_20180518_1945'),
    ]

    operations = [
    ]
