# Generated by Django 2.0.5 on 2018-05-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0023_merge_20180521_1809'),
        ('biz', '0023_auto_20180521_1458'),
    ]

    operations = [
    ]
