# Generated by Django 2.0.5 on 2018-05-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0024_merge_20180522_1411'),
        ('biz', '0024_merge_20180522_1406'),
    ]

    operations = [
    ]
