# Generated by Django 2.0.5 on 2018-05-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0023_auto_20180521_1458'),
        ('biz', '0025_auto_20180522_1137'),
    ]

    operations = [
    ]
