# Generated by Django 2.0.5 on 2018-05-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0024_merge_20180522_1358'),
        ('biz', '0025_merge_20180522_1421'),
    ]

    operations = [
    ]
