# Generated by Django 2.0.5 on 2018-05-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0026_merge_20180522_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_time',), 'verbose_name': '动态'},
        ),
        migrations.AlterField(
            model_name='boxeridentification',
            name='competition_video',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
