# Generated by Django 2.0.5 on 2018-05-22 11:56

import biz.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0026_merge_20180522_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('content', models.TextField(max_length=300)),
                ('images', biz.models.StringListField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='biz.PayOrder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_time',), 'verbose_name': '动态'},
        ),
        migrations.AlterField(
            model_name='boxeridentification',
            name='competition_video',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
