# Generated by Django 2.0.5 on 2018-05-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0026_merge_20180522_1526'),
        ('biz', '0025_auto_20180522_1430'),
    ]

    operations = [
    ]
