# Generated by Django 2.0.5 on 2018-05-22 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0026_merge_20180522_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('order_number', models.PositiveIntegerField()),
                ('link_type', models.SmallIntegerField(choices=[(1, 'app内网页跳转'), (2, 'app外网页跳转'), (3, 'app内本地跳转')])),
                ('link', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=200)),
                ('operator', models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'banner',
                'ordering': ('-order_number', '-created_time'),
            },
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_time',), 'verbose_name': '动态'},
        ),
        migrations.AlterField(
            model_name='boxeridentification',
            name='competition_video',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
