# Generated by Django 2.0.5 on 2018-05-23 02:19

import biz.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0027_merge_20180522_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('content', models.TextField(max_length=300)),
                ('images', biz.models.StringListField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='biz.PayOrder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_comment',
                'ordering': ('-created_time',),
            },
        ),
    ]
