# Generated by Django 2.0.5 on 2018-05-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0027_auto_20180522_1737'),
        ('biz', '0027_merge_20180522_1553'),
    ]

    operations = [
    ]
