# Generated by Django 2.0.5 on 2018-05-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0028_merge_20180522_1853'),
        ('biz', '0028_ordercomment'),
    ]

    operations = [
    ]
