# Generated by Django 2.0.5 on 2018-05-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0028_merge_20180522_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamenews',
            options={'ordering': ('-stay_top', '-created_time'), 'verbose_name': '赛事资讯'},
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
