# Generated by Django 2.0.5 on 2018-05-23 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0029_merge_20180523_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamenews',
            options={'ordering': ('-stay_top', '-created_time'), 'verbose_name': '赛事资讯'},
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='biz.PayOrder'),
        ),
    ]
