# Generated by Django 2.0.5 on 2018-05-24 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0029_auto_20180523_1858'),
        ('biz', '0030_auto_20180523_1843'),
    ]

    operations = [
    ]
