# Generated by Django 2.0.5 on 2018-05-25 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0031_auto_20180524_1948'),
        ('biz', '0031_merge_20180524_1218'),
    ]

    operations = [
    ]
