# Generated by Django 2.0.5 on 2018-05-25 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0031_merge_20180524_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSettleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('settled', models.BooleanField(default=False)),
                ('settled_date', models.DateField(null=True)),
                ('settled_amount', models.PositiveIntegerField(null=True)),
                ('course', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='biz.Course')),
                ('order', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='biz.PayOrder')),
            ],
            options={
                'db_table': 'course_settle_order',
                'ordering': ('-created_time',),
            },
        ),
    ]
