# Generated by Django 2.0.5 on 2018-05-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0032_merge_20180525_1416'),
        ('biz', '0032_coursesettleorder'),
    ]

    operations = [
    ]
