# Generated by Django 2.0.5 on 2018-05-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0033_withdrawlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawlog',
            name='order_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
