# Generated by Django 2.0.5 on 2018-05-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0033_withdrawlog'),
        ('biz', '0032_coursesettleorder'),
    ]

    operations = [
    ]
