# Generated by Django 2.0.5 on 2018-05-29 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0033_merge_20180528_1952'),
        ('biz', '0033_merge_20180528_1825'),
    ]

    operations = [
    ]
