# Generated by Django 2.0.5 on 2018-05-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0034_merge_20180528_1638'),
        ('biz', '0033_merge_20180528_1952'),
    ]

    operations = [
    ]
