# Generated by Django 2.0.5 on 2018-05-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0035_merge_20180528_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawlog',
            name='withdraw_account',
            field=models.CharField(max_length=30),
        ),
    ]
