# Generated by Django 2.0.5 on 2018-05-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0034_merge_20180529_1050'),
        ('biz', '0036_auto_20180529_1032'),
    ]

    operations = [
    ]
