# Generated by Django 2.0.5 on 2018-05-30 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0037_merge_20180529_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ancestor_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='ancestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='biz.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='biz.Comment'),
        ),
    ]
