# Generated by Django 2.0.5 on 2018-05-30 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0038_auto_20180530_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '约单'},
        ),
    ]
