# Generated by Django 2.0.5 on 2018-05-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0038_auto_20180530_1138'),
        ('biz', '0038_auto_20180530_1129'),
    ]

    operations = [
    ]
