# Generated by Django 2.0.5 on 2018-05-31 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0039_merge_20180530_1336'),
        ('biz', '0039_auto_20180530_1718'),
    ]

    operations = [
    ]
