# Generated by Django 2.0.5 on 2018-05-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0039_merge_20180530_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxingclub',
            name='city_first_letter',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
