# Generated by Django 2.0.5 on 2018-05-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0040_auto_20180531_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxingclub',
            name='city_index_letter',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
