# Generated by Django 2.0.5 on 2018-05-31 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0040_merge_20180531_1056'),
        ('biz', '0040_auto_20180531_1106'),
    ]

    operations = [
    ]
