# Generated by Django 2.0.5 on 2018-05-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0041_merge_20180531_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxingclub',
            name='city_index_letter',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
