# Generated by Django 2.0.5 on 2018-05-31 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0041_merge_20180531_1726'),
        ('biz', '0041_merge_20180531_1842'),
    ]

    operations = [
    ]
