# Generated by Django 2.0.5 on 2018-05-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0041_merge_20180531_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
