# Generated by Django 2.0.5 on 2018-05-31 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0041_merge_20180531_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialAccountChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.SmallIntegerField(choices=[(1, '充值'), (2, '提现'), (3, '约单'), (4, '热门视频')])),
                ('remarks', models.CharField(max_length=64)),
                ('related_user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'official_account_change_log',
                'ordering': ('-created_time',),
            },
        ),
    ]
