# Generated by Django 2.0.5 on 2018-05-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0042_boxingclub_city_index_letter'),
        ('biz', '0041_merge_20180531_1842'),
    ]

    operations = [
    ]
