# Generated by Django 2.0.5 on 2018-06-01 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0042_auto_20180531_1714'),
        ('biz', '0043_merge_20180531_1857'),
    ]

    operations = [
    ]
