# Generated by Django 2.0.5 on 2018-06-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0044_merge_20180601_1133'),
        ('biz', '0042_officialaccountchangelog'),
    ]

    operations = [
    ]
