# Generated by Django 2.0.5 on 2018-06-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0045_merge_20180601_1442'),
        ('biz', '0045_merge_20180601_1447'),
    ]

    operations = [
    ]
