# Generated by Django 2.0.5 on 2018-06-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0046_merge_20180601_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxeridentification',
            name='is_accept_order',
            field=models.BooleanField(default=True),
        ),
    ]
