# Generated by Django 2.0.6 on 2018-06-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0046_merge_20180601_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotvideo',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
