# Generated by Django 2.0.6 on 2018-06-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0047_auto_20180606_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamenews',
            name='share_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
