# Generated by Django 2.0.5 on 2018-06-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0048_auto_20180606_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nick_name_index_letter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
