# Generated by Django 2.0.5 on 2018-06-08 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0048_auto_20180606_1756'),
        ('biz', '0047_boxeridentification_is_accept_order'),
    ]

    operations = [
    ]
