# Generated by Django 2.0.6 on 2018-06-09 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0048_auto_20180606_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamenews',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
