# Generated by Django 2.0.6 on 2018-06-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0049_merge_20180608_1121'),
        ('biz', '0049_userprofile_nick_name_index_letter'),
    ]

    operations = [
    ]
