# Generated by Django 2.0.5 on 2018-06-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0048_auto_20180608_1521'),
        ('biz', '0049_merge_20180608_1121'),
    ]

    operations = [
    ]
