# Generated by Django 2.0.5 on 2018-06-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0049_merge_20180608_1121'),
        ('biz', '0047_auto_20180608_1048'),
    ]

    operations = [
    ]
