# Generated by Django 2.0.5 on 2018-06-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0047_auto_20180608_1048'),
        ('biz', '0050_merge_20180609_1335'),
    ]

    operations = [
    ]
