# Generated by Django 2.0.5 on 2018-06-10 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0050_merge_20180609_1335'),
        ('biz', '0051_auto_20180608_1811'),
    ]

    operations = [
    ]
