# Generated by Django 2.0.5 on 2018-06-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0051_merge_20180610_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorder',
            name='pay_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_order', to='biz.PayOrder'),
        ),
    ]
