# Generated by Django 2.0.5 on 2018-06-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0052_auto_20180610_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseorder',
            options={'ordering': ('-order_time',)},
        ),
    ]
