# Generated by Django 2.0.5 on 2018-06-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0052_merge_20180610_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorder',
            name='insurance_amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
