# Generated by Django 2.0.5 on 2018-06-12 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0053_auto_20180610_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseorder',
            options={'ordering': ('-order_time',), 'verbose_name': '约单'},
        ),
    ]
