# Generated by Django 2.0.5 on 2018-06-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0055_course_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorder',
            name='course_name',
            field=models.CharField(max_length=20),
        ),
    ]
