# Generated by Django 2.0.5 on 2018-06-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0056_auto_20180611_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxingclub',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='boxingclub',
            name='updated_time',
        ),
        migrations.AddField(
            model_name='boxingclub',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
