# Generated by Django 2.0.5 on 2018-06-12 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0054_auto_20180612_1144'),
        ('biz', '0057_auto_20180611_1737'),
    ]

    operations = [
    ]
