# Generated by Django 2.0.6 on 2018-06-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0049_auto_20180609_1328'),
        ('biz', '0058_merge_20180612_1446'),
    ]

    operations = [
    ]
