# Generated by Django 2.0.5 on 2018-06-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0059_auto_20180612_1824'),
        ('biz', '0059_merge_20180612_1726'),
    ]

    operations = [
    ]
