# Generated by Django 2.0.6 on 2018-06-13 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0060_merge_20180612_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesettleorder',
            name='course_order',
            field=models.ForeignKey(db_index=False, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='biz.CourseOrder'),
            preserve_default=False,
        ),
    ]
