# Generated by Django 2.0.5 on 2018-06-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0061_coursesettleorder_course_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('泰拳', '泰拳'), ('MMA', 'MMA'), ('拳击', '拳击')], max_length=20),
        ),
    ]
