# Generated by Django 2.0.5 on 2018-06-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0062_auto_20180614_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorder',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未支付'), (2, '已支付')], db_index=True, default=1),
        ),
    ]
