# Generated by Django 2.0.5 on 2018-06-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0063_auto_20180622_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxeridentification',
            name='is_accept_order',
            field=models.BooleanField(default=False),
        ),
    ]
