# Generated by Django 2.0.5 on 2018-06-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0063_auto_20180622_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
