# Generated by Django 2.0.5 on 2018-06-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0064_auto_20180622_1947'),
        ('biz', '0064_auto_20180622_1958'),
    ]

    operations = [
    ]
