# Generated by Django 2.0.6 on 2018-06-27 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0065_merge_20180622_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamenews',
            options={'ordering': ('-stay_top', '-updated_time'), 'verbose_name': '赛事资讯'},
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='updated_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
