# Generated by Django 2.0.6 on 2018-06-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0066_auto_20180627_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='updated_time',
            field=models.DateTimeField(null=True),
        ),
    ]
