# Generated by Django 2.0.5 on 2018-06-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0067_auto_20180627_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
