# Generated by Django 2.0.5 on 2018-06-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0067_auto_20180627_1900'),
        ('biz', '0068_handle_boxer_history_data'),
    ]

    operations = [
    ]
