# Generated by Django 2.0.6 on 2018-07-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0069_merge_20180627_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='initial_forward_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='initial_like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
