# Generated by Django 2.0.5 on 2018-06-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0069_merge_20180627_1951'),
        ('biz', '0068_courseorder_is_deleted'),
    ]

    operations = [
    ]
