# Generated by Django 2.0.5 on 2018-07-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0070_merge_20180628_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotvideo',
            name='cover',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
