# Generated by Django 2.0.6 on 2018-07-04 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0070_merge_20180628_1439'),
        ('biz', '0070_auto_20180703_1634'),
    ]

    operations = [
    ]
