# Generated by Django 2.0.6 on 2018-07-05 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0071_hotvideo_cover'),
        ('biz', '0071_merge_20180704_1153'),
    ]

    operations = [
    ]
