# Generated by Django 2.0.6 on 2018-07-10 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0074_auto_20180705_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotvideo',
            name='user',
        ),
        migrations.AddField(
            model_name='hotvideo',
            name='users',
            field=models.ManyToManyField(db_table='hot_video_user_rel', related_name='hot_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
