# Generated by Django 2.0.6 on 2018-07-10 11:33

from biz.constants import HOT_VIDEO_USER_ID
from django.db import migrations, models


def migrate_hot_video(apps, schema_editor):
    HotVideo = apps.get_model('biz', 'HotVideo')
    if HotVideo.objects.exists():
        hot_video_user = apps.get_model('biz', 'User').objects.get(id=HOT_VIDEO_USER_ID)
        for hot_video in HotVideo.objects.all():
            hot_video.users.add(hot_video_user)


class Migration(migrations.Migration):
    dependencies = [
        ('biz', '0075_auto_20180710_1933'),
    ]

    operations = [
        migrations.RunPython(migrate_hot_video)
    ]
