# Generated by Django 2.0.5 on 2018-07-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0077_auto_20180712_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fans',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
