# Generated by Django 2.0.7 on 2018-07-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0078_auto_20180720_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotvideo',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotvideo',
            name='tag',
            field=models.PositiveSmallIntegerField(choices=[(1, '默认标签')], default=1),
        ),
        migrations.AddField(
            model_name='hotvideo',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
