# Generated by Django 2.0.5 on 2018-07-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0079_add_fans_for_userprofile'),
        ('biz', '0078_auto_20180720_2217'),
    ]

    operations = [
    ]
