# Generated by Django 2.0.8 on 2018-09-03 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0080_merge_20180725_1443'),
        ('biz', '0079_auto_20180726_1534'),
    ]

    operations = [
    ]
