# Generated by Django 2.0.6 on 2018-09-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0081_merge_20180903_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotvideo',
            name='tag',
            field=models.PositiveSmallIntegerField(choices=[(1, '默认标签'), (2, '标签2'), (3, '标签3'), (4, '标签4')], default=1),
        ),
    ]
