# Generated by Django 2.0.8 on 2018-09-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0081_merge_20180903_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotvideo',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hotvideo',
            name='push_hot_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotvideo',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hotvideo',
            name='tag',
            field=models.PositiveSmallIntegerField(choices=[(1, '默认标签'), (2, '标签2'), (3, '标签3'), (4, '标签4')], default=1),
        ),
    ]
