# Generated by Django 2.0.8 on 2018-09-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0082_auto_20180903_1910'),
        ('biz', '0082_auto_20180903_1823'),
    ]

    operations = [
    ]
