# Generated by Django 2.0.8 on 2018-09-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='hotvideo',
            name='tag',
            field=models.PositiveSmallIntegerField(choices=[(1, '拳城出击'), (2, '徐晓冬'), (3, '教学'), (4, '街斗'), (5, '搞笑'), (6, '美女'), (7, '国外'), (8, '热点')], default=1),
        ),
    ]
