# Generated by Django 2.0.8 on 2018-09-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0083_merge_20180904_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotvideo',
            name='push_hot_video',
            field=models.BooleanField(),
        ),
    ]
