# Generated by Django 2.0.5 on 2018-09-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0081_album_albumpicture'),
        ('biz', '0083_merge_20180904_1719'),
    ]

    operations = [
    ]
