# Generated by Django 2.0.7 on 2018-09-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0084_merge_20180906_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumpicture',
            options={'ordering': ('-created_time',), 'verbose_name': '照片'},
        ),
    ]
