# Generated by Django 2.0.8 on 2018-09-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0081_auto_20180913_1727'),
        ('biz', '0085_auto_20180913_1438'),
    ]

    operations = [
    ]
