# Generated by Django 2.0.7 on 2018-09-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0085_auto_20180907_1421'),
        ('biz', '0084_merge_20180910_1102'),
    ]

    operations = [
    ]
