# Generated by Django 2.0.7 on 2018-09-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0086_merge_20180910_1444'),
        ('biz', '0084_auto_20180905_1634'),
    ]

    operations = [
    ]
