# Generated by Django 2.0.5 on 2018-09-11 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0087_merge_20180910_1756'),
        ('biz', '0085_auto_20180909_2216'),
    ]

    operations = [
    ]
