# Generated by Django 2.0.7 on 2018-09-20 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0086_merge_20180914_1426'),
        ('biz', '0087_merge_20180910_1756'),
    ]

    operations = [
    ]
