# Generated by Django 2.0.7 on 2018-09-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0087_auto_20180922_2207'),
        ('biz', '0088_merge_20180920_1102'),
    ]

    operations = [
    ]
