# Generated by Django 2.0.7 on 2018-09-12 08:44

import biz.validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0088_merge_20180911_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, '泰拳'), (2, '拳击'), (3, 'MMA')])),
                ('level', models.PositiveSmallIntegerField()),
                ('result', models.PositiveSmallIntegerField(choices=[(1, '红方胜'), (2, '蓝方胜'), (3, '红方KO蓝方'), (4, '蓝方KO红方')])),
            ],
            options={
                'db_table': 'match',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(db_index=True, error_messages={'unique': '手机号已存在。'}, max_length=11, unique=True, validators=[biz.validator.validate_mobile])),
                ('avatar', models.CharField(max_length=256)),
                ('stamina', models.PositiveIntegerField()),
                ('skill', models.PositiveIntegerField()),
                ('attack', models.PositiveIntegerField()),
                ('defence', models.PositiveIntegerField()),
                ('strength', models.PositiveIntegerField()),
                ('willpower', models.PositiveIntegerField()),
                ('operator', models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=127)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '未发布'), (2, '已发布')], default=1)),
                ('race_date', models.DateField()),
                ('operator', models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='blue_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_blue', to='biz.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='operator',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='red_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_red', to='biz.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='biz.Schedule'),
        ),
    ]
