# Generated by Django 2.0.7 on 2018-09-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0089_auto_20180912_1644'),
        ('biz', '0081_auto_20180913_1727'),
        ('biz', '0085_auto_20180913_1438'),
    ]

    operations = [
    ]
