# Generated by Django 2.0.7 on 2018-09-16 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0090_merge_20180913_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('-created_time',)},
        ),
    ]
