# Generated by Django 2.0.7 on 2018-09-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0091_auto_20180914_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, '泰拳'), (2, '拳击'), (3, 'MMA')], error_messages={'invalid_choice': '对战类型不符合要求!'}),
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.PositiveSmallIntegerField(choices=[(1, '红方胜'), (2, '蓝方胜'), (3, '红方KO蓝方'), (4, '蓝方KO红方')], error_messages={'invalid_choice': '对战结果不符合要求!'}),
        ),
    ]
