# Generated by Django 2.0.6 on 2018-09-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0090_merge_20180913_1833'),
        ('biz', '0092_auto_20180914_1603'),
    ]

    operations = [
    ]
