# Generated by Django 2.0.7 on 2018-09-17 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0091_auto_20180916_1925'),
        ('biz', '0093_merge_20180914_1648'),
    ]

    operations = [
    ]
