# Generated by Django 2.0.7 on 2018-09-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0094_merge_20180917_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, '泰拳'), (2, '拳击'), (3, 'MMA')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.PositiveSmallIntegerField(choices=[(1, '红方胜'), (2, '蓝方胜'), (3, '红方KO蓝方'), (4, '蓝方KO红方')]),
        ),
    ]
