# Generated by Django 2.0.7 on 2018-09-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0095_auto_20180917_1446'),
        ('biz', '0094_auto_20180917_1145'),
    ]

    operations = [
    ]
