# Generated by Django 2.0.8 on 2018-09-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0096_merge_20180917_1742'),
        ('biz', '0088_merge_20180920_1102'),
    ]

    operations = [
    ]
