# Generated by Django 2.0.8 on 2018-10-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0099_auto_20180930_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotvideo',
            name='initial_forward_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotvideo',
            name='initial_like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotvideo',
            name='initial_views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
