# Generated by Django 2.0.8 on 2018-10-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0090_auto_20181010_1053'),
        ('biz', '0099_auto_20180930_1623'),
    ]

    operations = [
    ]
