# Generated by Django 2.0.8 on 2018-10-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0100_merge_20181012_1428'),
        ('biz', '0101_gamenews_is_show'),
    ]

    operations = [
    ]
