# Generated by Django 2.0.8 on 2018-10-15 02:20

import biz.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0102_merge_20181012_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxeridentification',
            name='job',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='boxeridentification',
            name='real_name',
            field=models.CharField(max_length=30, validators=[biz.validator.validate_real_name]),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=30, validators=[biz.validator.validate_real_name]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[biz.validator.validate_real_name]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nation',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[biz.validator.validate_nation]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[biz.validator.validate_profession]),
        ),
    ]
