# Generated by Django 2.0.8 on 2018-10-15 03:31

import biz.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0103_auto_20181015_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxeridentification',
            name='job',
            field=models.CharField(max_length=30, validators=[biz.validator.validate_profession]),
        ),
    ]
