"""
Django settings for boxing_app project.

Generated by 'django-admin startproject' using Django 1.11.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

from settings import *

ROOT_URLCONF = 'boxing_app.urls'

WSGI_APPLICATION = 'boxing_app.wsgi.application'

REST_FRAMEWORK['DEFAULT_PAGINATION_CLASS'] = 'boxing_app.pagination.BoxingPagination'
