"""
Django settings for boxing_app project.

Generated by 'django-admin startproject' using Django 1.11.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ROOT_URLCONF = 'boxing_app.urls'

WSGI_APPLICATION = 'boxing_app.wsgi.application'

settings_common_file = os.path.join(BASE_DIR, 'common_settings.py')
if os.path.exists(settings_common_file):
    execfile(settings_common_file)
else:
    print "must exist common_settings.py in directory of {}".format(BASE_DIR)
    exit()
