
SENDING_VERIFY_CODE = "SENDING_VERIFY_CODE:{mobile}"
SEND_VERIFY_CODE = "SEND_VERIFY_CODE:{mobile}"
SEND_VERIFY_CODE_INTERVAL = 60
VERIFY_CODE_EXPIRED_INTERVAL = 300

REGISTER_INFO = "REGISTER:{mobile}"

# login
HAS_LOGINED = "LOGINED:{mobile}"
LOGIN_INTERVAL = 60

# easemob
EASEMOB_TOKEN = "EASEMOB_TOKEN"

# withdraw order number incr
WITHDRAW_ORDER_NUMBER_INCR = "WITHDRAW_ORDER_NUMBER_INCR"
