"""
Django settings for boxing_console project.

Generated by 'django-admin startproject' using Django 1.11.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

WSGI_APPLICATION = 'boxing_console.wsgi.application'

ROOT_URLCONF = 'boxing_console.urls'

settings_file = os.path.join(BASE_DIR, 'settings.py')
if not os.path.exists(settings_file):
    print "must exist settings.py in directory of {}".format(BASE_DIR)
    exit(1)
execfile(settings_file)